#:schema node_modules/wrangler/config-schema.json
name = "headwatersai"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "headwatersai-db"
database_id = ""